services:
  learn-docker:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: learn-docker-container_name
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=ref
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db # mongo-db is just a name it's not a place in memory, this is an anonymous volume
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   depends_on:
  #     - mongo
  redis: ## not necessirally to write "redis", you can have any name
    image: redis
    ports:
      - "6379:6379"
  web:
    image: nginx:1.26-alpine3.20
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - learn-docker
volumes:
  mongo-db:
